export const menuData = {
  menuHead: {
    title: "Empresa",
    createButton: { label: "Nuevo", action: () => {} },
  },
  menuSearch: { placeholder: "Buscar..." },
  menuItems: [
    {
      key: "dashboard",
      label: "Dashboard",
      icon: "Gauge",
      action: () => {},
      notification: 2,
      visible: true,
      ruta: "/empresa/",
    },
    {
      key: "empresas",
      label: "Empresas",
      icon: "Building2",
      action: () => {},
      notification: 0,
      visible: true,
      ruta: "/empresa/empresas",
    },
    {
      key: "clientes",
      label: "Clientes y Proveedores",
      icon: "Users",
      action: () => {},
      notification: 0,
      visible: true,
      ruta: "/empresa/clientes",
    },
    {
      key: "productos",
      label: "Productos y servicios",
      icon: "Package",
      action: () => {},
      notification: 0,
      visible: true,
      ruta: "/empresa/productos",
    },
    {
      key: "planes",
      label: "Planes recurrentes",
      icon: "Layers",
      action: () => {},
      notification: 0,
      visible: true,
      ruta: "/empresa/planes",
    },
    {
      key: "divider",
      label: "divider",
      visible: true,
    },
    {
      key: "invitaciones",
      label: "Invitaciones",
      icon: "UserPlus",
      action: () => {},
      notification: 2,
      visible: true,
      ruta: "/empresa/invitation",
    },
    {
      key: "seguridad",
      label: "Seguridad",
      icon: "ShieldCheck",
      action: () => {},
      notification: 0,
      visible: true,
      ruta: "/empresa/seguridad",
    },
    {
      key: "integraciones",
      label: "Integraciones",
      icon: "Plug",
      action: () => {},
      notification: 0,
      visible: true,
      ruta: "/empresa/integraciones",
    },
    {
      key: "divider",
      label: "divider",
      visible: true,
    },
    {
      key: "OrdenCompra",
      label: "Orden de Compra",
      icon: "ClipboardCheck",
      action: () => {},
      notification: 0,
      visible: true,
      ruta: "/empresa/OC",
    },
    {
      key: "OrdenVenta",
      label: "Orden de Venta",
      icon: "ClipboardList",
      action: () => {},
      notification: 0,
      visible: true,
    },
    {
      key: "BoletaHonorarios",
      label: "Boleta de Honorarios",
      icon: "FileSignature",
      action: () => {},
      notification: 0,
      visible: true,
    },
    {
      key: "FacturaElectronica",
      label: "Factura Electrónica",
      icon: "Receipt",
      action: () => {},
      notification: 0,
      visible: true,
    },
    {
      key: "dte",
      label: "DTE",
      icon: "Receipt",
      action: () => {},
      notification: 0,
      visible: false,
    },
  ],
  menuGroups: [],
};
