export const menuData = {
  menuHead: {
    title: "Configuración",
    createButton: { label: "Nuevo", action: () => {} },
  },
  menuSearch: { placeholder: "Buscar..." },
  menuItems: [
    {
      key: "profile",
      label: "Perfil",
      icon: "UserCircle",
      action: () => {},
      notification: 0,
      visible: true,
      ruta: "/settings/profile",
    },
    {
      key: "billing",
      label: "Facturación",
      icon: "Receipt",
      action: () => {},
      notification: 0,
      visible: true,
      ruta: "/settings/billing",
    },
    { key: "divider", label: "divider", visible: true },
    {
      key: "notifications",
      label: "Notificaciones",
      icon: "Bell",
      action: () => {},
      notification: 5,
      visible: true,
      ruta: "/settings/notifications",
    },
    {
      key: "system",
      label: "Sistema",
      icon: "Settings",
      action: () => {},
      notification: 0,
      visible: true,
      ruta: "#/settings/system",
    },
  ],
  menuGroups: [
    {
      groupKey: "maestros",
      groupLabel: "Maestros",
      groupAdd: true,
      items: [
        {
          key: "company",
          label: "Proveedores y clientes",
          icon: "Store",
          notification: 12,
          action: () => {},
          ruta: "/settings/company",
        },
        {
          key: "clientes",
          label: "Clientes",
          icon: "Users",
          notification: 2,
          action: () => {},
        },
        {
          key: "proveedores",
          label: "Proveedores",
          icon: "Users",
          notification: null,
          action: () => {},
        },
      ],
    },
    {
      groupKey: "System",
      groupLabel: "Sistema",
      groupAdd: false,
      items: [
        {
          key: "sistema",
          label: "Sistema",
          icon: "Cog",
          notification: 12,
          action: () => {},
        },
        {
          key: "invitaciones",
          label: "Invitaciones",
          icon: "ShieldUser",
          notification: 1,
          action: () => {},
        },
        {
          key: "plugins",
          label: "Integraciones",
          icon: "Unplug",
          notification: null,
          action: () => {},
        },
      ],
    },
  ],
};
